# To help us make Dependabot better, we're regularily contacting users for feedback.
# If you would like to be excluded from these emails, please contact us at dependabot-feedback@github.com

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - "dependencies"
      - "security"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
